<?php

/**
 * @file
 * The entity_reference_override hook implementations.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\entity_reference_override\Exception\ReadOnlyEntityException;

/**
 * Implements hook_entity_presave().
 */
function entity_reference_override_entity_presave(EntityInterface $entity) {
  if (isset($entity->entity_reference_override)) {
    throw new ReadOnlyEntityException(sprintf('The entity (ID: %s, entity_type: %s) is overridden and not allowed to be saved.', $entity->id(), $entity->getEntityTypeId()));
  }
}

/**
 * Implements hook_field_widget_info_alter().
 */
function entity_reference_override_field_widget_info_alter(array &$info) {
  $info['entity_reference_autocomplete_tags']['field_types'][] = 'entity_reference_override';
  $info['entity_reference_autocomplete']['field_types'][] = 'entity_reference_override';
  $info['options_buttons']['field_types'][] = 'entity_reference_override';
  $info['options_select']['field_types'][] = 'entity_reference_override';

  if (\Drupal::moduleHandler()->moduleExists('media_library')) {
    $info['media_library_with_override_widget']['class'] = '\Drupal\entity_reference_override\MediaLibraryWithOverrideWidget';
  }
  else {
    // The widget is useless without media library so remove it.
    unset($info['media_library_with_override_widget']);
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function entity_reference_override_field_formatter_info_alter(array &$info) {
  $info['entity_reference_entity_view']['field_types'][] = 'entity_reference_override';
  $info['entity_reference_entity_id']['field_types'][] = 'entity_reference_override';
  $info['entity_reference_label']['field_types'][] = 'entity_reference_override';
}

/**
 * Implements hook_entity_build_defaults_alter().
 */
function entity_reference_override_entity_build_defaults_alter(array &$build, EntityInterface $entity, $view_mode) {
  if (isset($entity->entity_reference_override)) {
    $build['#cache']['keys'][] = 'entity_reference_override:' . $entity->entity_reference_override;
  }
}
